# Generated by Django 4.0.2 on 2022-02-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
